# Generated by Django 5.1.5 on 2025-01-30 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, verbose_name='Telefon')),
                ('address', models.CharField(max_length=100, verbose_name='Adres')),
                ('is_loan', models.BooleanField(default=False, verbose_name='Borçlu ?')),
                ('bought', models.PositiveIntegerField(default=0, verbose_name='Toplam satın aldığı ürün adeti')),
                ('total_loan', models.FloatField(default=0, verbose_name='Toplam Borç')),
                ('total_pay', models.FloatField(default=0, verbose_name='Toplam Harcamalar')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Katılma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(db_index=True, unique=True, verbose_name='Sipariş Numarası')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Aldığı ürün miktarı')),
                ('cost', models.FloatField(blank=True, default=0, null=True, verbose_name='Ödeme Girişi')),
                ('total', models.FloatField(default=0, verbose_name='Toplam')),
                ('remain', models.FloatField(default=0, verbose_name='Kalan tutar')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Son Ödeme Tarihi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-order_date'],
            },
        ),
    ]
