# Generated by Django 5.1.5 on 2025-01-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ödediği Tutar'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Satın aldığı tarih'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Aldığı ürün miktarı'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kalan tutar'),
        ),
    ]
