# Generated by Django 5.1.5 on 2025-01-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment',
            field=models.CharField(choices=[('cash', 'Nakit'), ('cart', 'Cart'), ('loan', 'Loan')], default='cart', max_length=5),
        ),
    ]
