# Generated by Django 5.1.5 on 2025-01-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_ordermodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment',
            field=models.CharField(choices=[('Kredi Kartı', 'Kredi Kartı'), ('Nakit', 'Nakit'), ('Borç', 'Borç')], default='Kredi Kartı', max_length=11, verbose_name='Ödeme Yöntemi'),
        ),
    ]
