# Generated by Django 5.1.5 on 2025-01-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingssite',
            name='favicon',
            field=models.ImageField(null=True, upload_to='favicon', verbose_name='Favicon'),
        ),
    ]
