# Generated by Django 5.1.5 on 2025-01-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingssite',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='settingssite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='settingssite',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone No'),
        ),
    ]
