# Generated by Django 5.1.5 on 2025-01-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi'),
        ),
    ]
