# Generated by Django 5.1.5 on 2025-01-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session_key',
            new_name='cart_number',
        ),
    ]
