# Generated by Django 5.1.5 on 2025-01-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0002_settingssite_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingssite',
            name='card',
            field=models.CharField(blank=True, choices=[('blog', 'BLOG'), ('album', 'ALBUM')], default='blog', max_length=11, verbose_name='Cart Türü Seçiniz'),
        ),
        migrations.AlterField(
            model_name='settingssite',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon', verbose_name='Favicon'),
        ),
    ]
