# Generated by Django 5.1.5 on 2025-01-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0002_settingssite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingssite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Adres'),
        ),
        migrations.AlterField(
            model_name='settingssite',
            name='email_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email Şifresi'),
        ),
    ]
