# Generated by Django 5.1.5 on 2025-01-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0002_rename_session_key_cart_cart_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Sipariş verildi mi ?'),
        ),
    ]
