# Generated by Django 5.1.5 on 2025-01-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0002_alter_contact_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casemodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Kasa', 'verbose_name_plural': 'Kasa'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created'], 'verbose_name': 'İletişim', 'verbose_name_plural': 'İletişim'},
        ),
        migrations.AlterField(
            model_name='casemodel',
            name='created_at',
            field=models.DateTimeField(auto_created=True, verbose_name='Ödeme Tarihi'),
        ),
    ]
