# Generated by Django 5.1.5 on 2025-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0002_settingssite_address_settingssite_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settingssite',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefon No'),
        ),
    ]
