# Generated by Django 5.1.5 on 2025-01-21 19:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique_with=('created',)),
        ),
    ]
