# Generated by Django 5.1.5 on 2025-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0003_contact_is_read_alter_settingssite_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Okundu ?'),
        ),
    ]
