# Generated by Django 5.1.5 on 2025-01-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0003_alter_cart_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son ödeme tarihi'),
        ),
    ]
