# Generated by Django 5.1.5 on 2025-01-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0003_alter_settingssite_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Duyuru', 'verbose_name_plural': 'Duyuru'},
        ),
    ]
