# Generated by Django 5.1.5 on 2025-01-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0004_alter_header_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
