# Generated by Django 5.1.5 on 2025-01-23 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0005_alter_cart_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Son ödeme tarihi'),
        ),
    ]
