# Generated by Django 5.1.5 on 2025-01-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0006_alter_casemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi'),
        ),
    ]
