# Generated by Django 5.1.5 on 2025-01-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayi', '0006_alter_cart_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_number',
            field=models.CharField(max_length=100, verbose_name='Sepet ID'),
        ),
    ]
